steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/project-shubh-1/emarket-repo/emarket:latest', './App']
  id: 'Build and Tag Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/project-shubh-1/emarket-repo/emarket:latest']
  id: 'Push Docker Image'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'  # Use 'bash' as the entrypoint
  args: 
    - '-c' # To execute a command string
    - |  # Use the pipe symbol for multi-line strings
      RELEASE_NAME="emarket-release-$(date +%Y%m%d%H%M%S)"
      gcloud deploy releases create "$RELEASE_NAME" \
          --delivery-pipeline=emarket-pipeline \
          --region=us-central1 \
          --annotations=image-URI=us-central1-docker.pkg.dev/project-shubh-1/emarket-repo/emarket:latest
  id: 'Create Cloud Deploy Release'

images:
- 'us-central1-docker.pkg.dev/project-shubh-1/emarket-repo/emarket:latest'