steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/project-shubh-1/emarket/emarket:$COMMIT_SHA', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/project-shubh-1/emarket/emarket:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/kubectl'
  args: ['set', 'image', 'deployment/emarket', 'emarket=us-central1-docker.pkg.dev/project-shubh-1/emarket/emarket:$COMMIT_SHA', '-n', 'my-standard-cluster']
images:
- 'us-central1-docker.pkg.dev/project-shubh-1/emarket/emarket:$COMMIT_SHA'