steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/emarket-repo/emarket:$COMMIT_SHA', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/emarket-repo/emarket:latest', '.']
  id: 'Build and Tag Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/emarket-repo/emarket:$COMMIT_SHA']  
  id: 'Push Docker Image with Commit SHA'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/emarket-repo/emarket:latest']
  id: 'Push Docker Image with Latest Tag'