steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/emarket/emarket:$COMMIT_SHA', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/emarket/emarket:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/emarket/emarket:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/emarket/emarket:latest']
