steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/project-shubh-1/emarket-repo/emarket:latest', './App'] # Add :latest tag
  id: 'Build and Tag Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/project-shubh-1/emarket-repo/emarket:latest'] # Add :latest tag
  id: 'Push Docker Image'

- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'bash'
  args:
  - -c
  - |
    gcloud deploy releases create release-$BUILD_ID \
      --delivery-pipeline=emarket-pipeline \
      --region=us-central1 \
      --images=my-app-image=us-central1-docker.pkg.dev/project-shubh-1/emarket-repo/emarket:latest # Add :latest tag
      --source=./emarket

images:
- 'us-central1-docker.pkg.dev/project-shubh-1/emarket-repo/emarket:latest' # Add this line