steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/emarket/emarket:$COMMIT_SHA', '-t', 'us-central1-docker.pkg.dev/$PROJECT_ID/emarket/emarket:latest', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/emarket/emarket:$COMMIT_SHA']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/$PROJECT_ID/emarket/emarket:latest']
- name: 'gcr.io/cloud-builders/kubectl'
  env:
  - 'CLOUDSDK_COMPUTE_REGION=us-central1'
  - 'CLOUDSDK_CONTAINER_CLUSTER=non-prod-cluster'
  args: ['set', 'image', 'deployment/non-prod-gke', 'non-prod-gke=us-central1-docker.pkg.dev/project-shubh-1/emarket/emarket:latest', '-n', 'default']
images:
- 'us-central1-docker.pkg.dev/$PROJECT_ID/emarket/emarket:$COMMIT_SHA'
- 'us-central1-docker.pkg.dev/$PROJECT_ID/emarket/emarket:latest'