steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/project-shubh-1/emarket-repo/emarket:latest', './App'] # Add :latest tag
  id: 'Build and Tag Docker Image'

- name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'us-central1-docker.pkg.dev/project-shubh-1/emarket-repo/emarket:latest']
  id: 'Push Docker Image'

images:
- 'us-central1-docker.pkg.dev/project-shubh-1/emarket-repo/emarket:latest'