apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-app 
spec:
  replicas: 3 # Number of pods you want to run
  selector:
    matchLabels:
      app: my-app
  template:
    metadata:
      labels:
        app: my-app
    spec:
      containers:
      - name: my-app
        image: us-central1-docker.pkg.dev/project-shubh-1/emarket/image1:gcpimage
        ports:
        - containerPort: 80