apiVersion: deploy.cloud.google.com/v1
kind: DeliveryPipeline
metadata:
  name: my-pipeline
serialPipeline:
  stages:
  - targetId: non-prod
    profiles: []
  - targetId: prod
    profiles: []
    predeploy:
      requireApproval: true 

---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: non-prod
description: Non-production environment
gke:
  cluster: projects/project-shubh-1/locations/us-central1/clusters/non-prod-cluster 
---
apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: prod
description: Production environment
gke:
  cluster: projects/project-shubh-1/locations/us-central1/clusters/prod-cluster