apiVersion: deploy.cloud.google.com/v1
kind: Target
metadata:
  name: nonprod-gke-1
  description: non production cluster
gke:
  cluster: projects/project-shubh-1/locations/us-central1/clusters/non-prod-cluster