apiVersion: apps/v1
kind: Deployment
metadata:
  name: non-prod-gke1 
spec:
  replicas: 2
  selector:
    matchLabels:
      app: emarket 
  template:
    metadata:
      labels:
        app: emarket 
    spec:
      containers:
      - name: emarket 
        image: us-central1-docker.pkg.dev/project-shubh-1/emarket-repo/emarket:latest  # Add your full image name with tag
        ports:
        - containerPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: emarket-service  # Match the service name to your deployment
spec:
  selector:
    app: emarket   # Match the selector to your deployment
  type: LoadBalancer
  ports:
  - protocol: TCP   # Add protocol for clarity
    port: 80
    targetPort: 80